import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ActiveLink } from "@/ui/atoms/ActiveLink";
import { getCategoryList } from "@/api/categories";
import { SearchInput } from "@/ui/organisms/SearchInput";
import { CartQuantity } from "@/ui/organisms/CartQuantity";

const inter = Inter({ subsets: ["latin", "latin-ext"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
	modal,
}: {
	children: React.ReactNode;
	modal: React.ReactNode;
}) {
	const categories = await getCategoryList();

	return (
		<html lang="en">
			<body className={inter.className}>
				<nav className="m-4 flex justify-between">
					<div className="flex gap-3">
						<SearchInput />
						<div className="flex items-center justify-end whitespace-nowrap">
							<CartQuantity />
						</div>
					</div>
					<ul className=" mx-4 my-3 flex w-full flex-row justify-end gap-4">
						<li>
							<ActiveLink href="/">Home</ActiveLink>
						</li>
						<li>
							<ActiveLink href="/products" exact={false}>
								All
							</ActiveLink>
						</li>
						{categories.map((category) => (
							<li key={category.id}>
								<ActiveLink href={`/categories/${category.name}`} exact={false}>
									{category.name}
								</ActiveLink>
							</li>
						))}
					</ul>
				</nav>
				<section className="mx-auto max-w-md p-12 sm:max-w-2xl sm:py-16 md:max-w-4xl lg:max-w-7xl">
					{children}
				</section>
				<footer className="mx-auto text-center">
					<p>Next13Masters Shop - 2023 - All rights reserved</p>
				</footer>
				{modal}
			</body>
		</html>
	);
}
